include(CMakePrintHelpers)

message(STATUS "")
message(STATUS "========================================================")
message(STATUS "              ${PROJECT_NAME} ${PROJECT_VERSION}")
message(STATUS "========================================================")
message(STATUS "")
message(STATUS "Build type          : ${CMAKE_BUILD_TYPE}")
message(STATUS "Compiler            : ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "C++ standard        : ${CMAKE_CXX_STANDARD}")
message(STATUS "")
message(STATUS "Generator           : ${CMAKE_GENERATOR}")
message(STATUS "System              : ${CMAKE_SYSTEM_NAME}")
message(STATUS "Processor           : ${CMAKE_SYSTEM_PROCESSOR}")
message(STATUS "")
message(STATUS "Install prefix      : ${CMAKE_INSTALL_PREFIX}")
message(STATUS "")
message(STATUS "Shared libraries    : ${BUILD_SHARED_LIBS}")
message(STATUS "Tests               : ${BUILD_TESTING}")
message(STATUS "Examples            : ${BUILD_EXAMPLES}")
message(STATUS "Documentation       : ${BUILD_DOCS}")
message(STATUS "")
message(STATUS "Check documentation : ${ENABLE_CHECK_DOC}")
message(STATUS "Check format        : ${ENABLE_CLANG_FORMAT}")
message(STATUS "Check tidy          : ${ENABLE_CLANG_TIDY}")


message(STATUS "")
message(STATUS "Git tag     : ${PROJECT_GIT_TAG}")
message(STATUS "Git hash    : ${PROJECT_GIT_HASH}")
message(STATUS "========================================================")
message(STATUS "")