name: CD

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Create release

    runs-on: ubuntu-latest
    container:
      image: gcc:15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt update
          apt install -y \
            cmake \
            ninja-build

      - name: Configure release
        run: |
          cmake --preset release

      - name: Build release
        run: |
          cmake --build --preset release

      - name: Package
        run: |
          cmake --install build/release \
            --prefix package

      - name: Archive package
        run: |
          tar czf XXX-${GITHUB_REF_NAME}.tar.gz package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            XXX-${GITHUB_REF_NAME}.tar.gz
          generate_release_notes: true