name: Code Quality


on:

  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop



jobs:


  commit-check:

    name: Commit convention


    runs-on: ubuntu-latest
    container:
      image: gcc:15


    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Install Commitizen
        run: |
          pip install commitizen


      - name: Check commits
        run: |
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            cz check --rev-range "${{ github.sha }}"
          else
            cz check --rev-range "${{ github.event.before }}..${{ github.sha }}"
          fi



  clang-format:

    name: clang-format check

    runs-on: ubuntu-latest
    container:
      image: gcc:15

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Install clang-format
        run: |
          sudo apt update
          sudo apt install -y clang-format


      - name: Check formatting
        run: |
          clang-format \
            --dry-run \
            --Werror \
            $(find . \
              \( -name "*.cpp" \
              -o -name "*.hpp" \
              -o -name "*.h" \) \
              -not -path "./build/*")



  clang-tidy:

    name: Static analysis


    runs-on: ubuntu-latest
    container:
      image: gcc:15

    steps:


      - name: Checkout
        uses: actions/checkout@v4



      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            ninja-build \
            clang-tidy



      - name: Configure
        run: |
          cmake --preset debug \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON



      - name: Build compile database
        run: |
          cmake --build --preset debug



      - name: Run clang-tidy
        run: |
          clang-tidy \
            $(find src tests \
              \( -name "*.cpp" \)) \
            -p build/debug